// Generated by scripts/make-brand-assets.swift. Edit the generator, then regenerate.
import SwiftUI

struct JanusMark: Shape {
    private static let geometry: CGPath = {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 45.354, y: 8.000))
        path.addCurve(to: CGPoint(x: 14.769, y: 25.662), control1: CGPoint(x: 32.646, y: 6.923), control2: CGPoint(x: 17.354, y: 15.754))
        path.addCurve(to: CGPoint(x: 14.769, y: 30.400), control1: CGPoint(x: 13.908, y: 28.246), control2: CGPoint(x: 16.277, y: 28.031))
        path.addLine(to: CGPoint(x: 10.677, y: 37.723))
        path.addCurve(to: CGPoint(x: 9.815, y: 40.954), control1: CGPoint(x: 9.815, y: 39.015), control2: CGPoint(x: 9.169, y: 40.092))
        path.addCurve(to: CGPoint(x: 13.692, y: 43.323), control1: CGPoint(x: 10.462, y: 42.246), control2: CGPoint(x: 13.692, y: 41.600))
        path.addCurve(to: CGPoint(x: 13.908, y: 46.769), control1: CGPoint(x: 13.908, y: 44.400), control2: CGPoint(x: 13.046, y: 45.908))
        path.addCurve(to: CGPoint(x: 14.123, y: 48.708), control1: CGPoint(x: 13.046, y: 47.631), control2: CGPoint(x: 13.262, y: 48.277))
        path.addLine(to: CGPoint(x: 15.200, y: 49.354))
        path.addCurve(to: CGPoint(x: 15.415, y: 51.938), control1: CGPoint(x: 14.338, y: 50.431), control2: CGPoint(x: 14.338, y: 51.292))
        path.addCurve(to: CGPoint(x: 16.708, y: 56.462), control1: CGPoint(x: 16.923, y: 53.231), control2: CGPoint(x: 17.569, y: 54.738))
        path.addCurve(to: CGPoint(x: 21.662, y: 61.631), control1: CGPoint(x: 15.846, y: 59.692), control2: CGPoint(x: 17.138, y: 61.631))
        path.addLine(to: CGPoint(x: 45.354, y: 61.631))
        path.addLine(to: CGPoint(x: 45.354, y: 37.292))
        path.addLine(to: CGPoint(x: 33.723, y: 37.292))
        path.addCurve(to: CGPoint(x: 45.354, y: 23.723), control1: CGPoint(x: 32.431, y: 32.985), control2: CGPoint(x: 37.385, y: 26.523))
        path.closeSubpath()
        path.move(to: CGPoint(x: 53.538, y: 37.292))
        path.addLine(to: CGPoint(x: 77.231, y: 37.292))
        path.addCurve(to: CGPoint(x: 81.538, y: 41.385), control1: CGPoint(x: 80.031, y: 37.292), control2: CGPoint(x: 81.108, y: 38.800))
        path.addLine(to: CGPoint(x: 84.554, y: 46.985))
        path.addCurve(to: CGPoint(x: 85.200, y: 51.723), control1: CGPoint(x: 85.846, y: 49.354), control2: CGPoint(x: 84.123, y: 50.000))
        path.addLine(to: CGPoint(x: 89.723, y: 58.400))
        path.addCurve(to: CGPoint(x: 86.923, y: 61.631), control1: CGPoint(x: 91.015, y: 60.338), control2: CGPoint(x: 89.508, y: 61.200))
        path.addCurve(to: CGPoint(x: 85.846, y: 64.646), control1: CGPoint(x: 85.631, y: 61.846), control2: CGPoint(x: 85.415, y: 63.138))
        path.addCurve(to: CGPoint(x: 84.123, y: 67.231), control1: CGPoint(x: 86.277, y: 65.938), control2: CGPoint(x: 85.200, y: 66.800))
        path.addLine(to: CGPoint(x: 84.985, y: 68.308))
        path.addCurve(to: CGPoint(x: 83.262, y: 71.538), control1: CGPoint(x: 85.200, y: 69.600), control2: CGPoint(x: 84.123, y: 70.677))
        path.addCurve(to: CGPoint(x: 82.400, y: 76.277), control1: CGPoint(x: 81.969, y: 72.615), control2: CGPoint(x: 83.262, y: 74.338))
        path.addCurve(to: CGPoint(x: 77.231, y: 80.154), control1: CGPoint(x: 81.969, y: 79.077), control2: CGPoint(x: 79.600, y: 80.154))
        path.addCurve(to: CGPoint(x: 52.892, y: 92.000), control1: CGPoint(x: 71.631, y: 86.831), control2: CGPoint(x: 63.662, y: 91.785))
        path.addLine(to: CGPoint(x: 52.892, y: 75.415))
        path.addCurve(to: CGPoint(x: 64.954, y: 62.062), control1: CGPoint(x: 59.354, y: 73.262), control2: CGPoint(x: 64.308, y: 68.308))
        path.addLine(to: CGPoint(x: 53.538, y: 62.062))
        path.closeSubpath()
        return path
    }()

    func path(in rect: CGRect) -> Path {
        var transform = CGAffineTransform(a: rect.width / 100, b: 0, c: 0, d: rect.height / 100,
                                         tx: rect.minX, ty: rect.minY)
        return Path(Self.geometry.copy(using: &transform)!)
    }

    @MainActor static let menuBarImage: NSImage = {
        let image = NSImage(size: NSSize(width: 20, height: 20), flipped: true) { rect in
            let context = NSGraphicsContext.current!.cgContext
            context.saveGState()
            context.scaleBy(x: rect.width / 100, y: rect.height / 100)
            context.setFillColor(NSColor.black.cgColor)
            context.addPath(geometry)
            context.fillPath()
            context.restoreGState()
            return true
        }
        image.isTemplate = true
        return image
    }()
}
